accounts/urls.py
from django.urls import path
from . import views

app_name ='accounts'

urlpatterns =[
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote')
]

subject_register/urls.py
from django.urls import path
from . import views

app_name = 'subject_register'

urlpatterns = [
    path('index', views.IndexView.as_view(), name='index')
]

testdev/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('',include('accounts.urls')),
    path('subject_register/',include('subject_register.urls')),
    path('admin/', admin.site.urls),
    path('site_junction/',include('site_junction.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

subject_register/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import inspect

ls=[(0,'一般'),(1,'M'),(2,'E'),(3,'D'),(4,'J'),(5,'C')]

class Subject(models.Model):
    course = models.IntegerField(choices=ls)
    grade = models.IntegerField()
    select = models.BooleanField()
    title = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    credit = models.IntegerField()
    url = models.URLField(blank=True)
    students = models.ManyToManyField(User,related_name='subjects',blank=True)
    def __str__(self):
        return self.title

class Form(models.Model):
    course = models.IntegerField(choices=ls)
    grade = models.IntegerField()
    def __str__(self):
        return ls[self.course][1] + str(self.grade)

class Option(models.Model):
    form = models.ForeignKey(Form,on_delete=models.CASCADE)
    subject = models.OneToOneField(Subject,on_delete=models.CASCADE,null=True)
    title = models.CharField(max_length=64,blank=True)
    def __str__(self):
        return self.title

@receiver(post_save, sender=Option)
def make_option_title(sender,instance, **kwargs):
    if kwargs['created']:
        instance.title = instance.subject.title
        instance.save()

accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm 

class LoginForm(AuthenticationForm):
    # ログインフォーム
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

subject_register/forms.py
from django import forms
from .models import Option

class VoteForm(forms.Form):
    choice = forms.MultipleChoiceField(label = "科目",widget=forms.CheckboxSelectMultiple())
    class Meta:
        model = Option
        fields = "__all__"

    def __init__(self,categories=None,*args,**kwargs):
        self.base_fields['choice'].choices = categories
        super().__init__(*args,**kwargs)    

accounts/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import(LoginView, LogoutView)
from .forms import LoginForm

class Login(LoginView):
    # ログインページ
    form_class = LoginForm
    template_name = 'accounts/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    # ログアウトページ
    template_name = 'accounts/login.html'

polls/views.py
from django.shortcuts import render , get_object_or_404
from django.http import HttpResponse , Http404 , HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.views import generic

from .models import Question , Choice

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

subject_register/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from .models import Subject,Option
from .forms import VoteForm
from django.urls import reverse_lazy
from django.contrib.auth.models import User
import logging

class IndexView(FormView):
    template_name = 'subject_register/index.html'
    form_class = VoteForm
    success_url = 'index'

    def get_form_kwargs(self,*args,**kwargs):
        kwgs = super().get_form_kwargs(*args,**kwargs)
        products = Option.objects.values_list('title',flat=True)
        choice_ls = [(product,product) for product in products]
        kwgs['categories'] = choice_ls
        return kwgs

    def form_valid(self,form):
        message = f"{form.cleaned_data['choice']}"
        context = {'form':form,'msg':message}
        for f in form.cleaned_data['choice']:
            opt = Option.objects.filter(title=f)[0]
            opt.subject.students.add(self.request.user)
            opt.subject.save()
        return render(self.request,self.template_name,context)

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Course Application System</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
  <div class="login-box">
    <div class="login-logo">
      <b>履修申請システム</b>
    </div>
    <!-- /.login-logo -->
    <div class="login-box-body">
      <p class="login-box-msg"><b>ログイン</b></p>

      <form action="" method="POST">
        {% csrf_token %}
        {% for field in form %}
          <div class="form-group has-feedback">
            {{ field }}
          </div>
        {% endfor %}
        <div class="row">

          {% for error in form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              <p>{{ error }}</p>
            </div>
          {% endfor %}
          <!-- /.col -->
          <div class="col-xs-4">
            <button type="submit" class="btn btn-primary btn-block btn-flat">ログイン</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
    </div>
    <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->

</body>
</html>

polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

site_junction/templates/site_junction/link_page.html
<html>
  <head>
    <title>Link Junction Page</title>
  </head>
  <body>
    <h1>
      <p>links</p>
      <ul>
        <li><a href="../login/">login</a></li>
        <li><a href="../logout/">logout</a></li>
        <li><a href="../subject_register">履修申請</li>
      </ul>
    </h1>
  </body>
</html>

subject_register/templates/subject_register/index.html
<body>
    <form method='POST'>
        {% csrf_token %}
        <table>
            {{ form.as_table}}
        </table>
        <button type='submit'>申請</button>
    </form>
    {{ msg }}
</body>